### PR TITLE
Addressing compatibility issues

### PR DESCRIPTION
**Pull request by pitampoudel**

### CODE REVIEW

**Comment by pitampoudel** [comment]
Everything is okay to merge this pull request except the publish scripts commented (2 lines) and proguard disabled (1 line) changes

**Comment by ishowrunes** [comment]
Please also state the reasoning behind this PR

**Comment by pitampoudel** [comment]
@Ishwor-Shrestha I was not even able to build the project due to a lot of conflicts of dependencies

**Comment by pitampoudel** [comment]
Closing this as we discussed the new release on March 20

**Pull request closed without merging**
